image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/sando38/helm-ejabberd
  tag: 24.12-k8s1@sha256:0b2c31d3236de9dcf5b34f541f1e4ce77aad6a94ee60cb8923ecb88e65a6d990
workload:
  main:
    podSpec:
     containers:
        main:
          securityContext:
            runAsNonRoot: true
            runAsUser: 9000
            runAsGroup: 9000
service:
  main:
    ports:
      main:
        enabled: true
        protocol: http
        targetPort: 5280
        port: 5280
      xmpp:
        enabled: true
        protocol: tcp
        targetPort: 5222
        port: 5222
      xmpp_federation:
        enabled: false
        protocol: tcp
        targetPort: 5269
        port: 5269
persistence:
  data:
    enabled: true
    mountPath: /opt/ejabberd/database/
  # conf:
  #   enabled: false
  #   type: configmap
  #   mountPath: /opt/ejabberd/conf/ejabberd.yml
  #   object-name: configuration
  #   readOnly: true
  conf:
    enabled: false
    type: configmap
    mountPath: /opt/ejabberd/conf/
  upload:
    enabled: true
    mountPath: /opt/ejabberd/upload/
  logs:
    enabled: false
    mountPath: /opt/ejabberd/logs/

# configmap:
#   conf:
#     enabled: true
#     data: {}


